import { VisitReport } from "../types/types";

export const visitReport: VisitReport[] = [
  {
    visitDate: "27/01/2024",
    name: "Natural Creations, Inc.",
    customerName: "Dibbert-Langworth",
    id: 84344,
    city: "Pasto",
    address: "544 Eagle Crest Place",
    phoneNumber: "740-712-2323",
    email: "mstokell0@nydailynews.com",
    dueDate: "15/06/2023",
    priority: "Alta",
    workforce: {
      worforce1: 8,
      worforce2: 5,
      worforce3: 7,
      worforce4: 9,
    },
    materials: {
      material1: 2,
      material2: 5,
      material3: 3,
      material4: 8,
      material5: 7,
    },
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, veniam magni. Omnis sunt quaerat quidem, perferendis animi harum laboriosam dolorem reprehenderit vel est adipisci rerum magnam nulla itaque eaque dignissimos doloremque fuga. Odit et voluptatibus ipsa voluptatum consequuntur? Sunt accusamus tempora ea ratione officiis excepturi ipsa perspiciatis repellendus reprehenderit sapiente.",
  },
  {
    visitDate: "17/01/2024",
    name: "AMI Cosmetic Co.,Ltd.",
    customerName: "Wilkinson, Berge and Pfannerstill",
    id: 54937,
    city: "Bucaramanga",
    address: "2458 Bowman Avenue",
    phoneNumber: "234-724-5248",
    email: "jroffey1@japanpost.jp",
    dueDate: "07/06/2024",
    priority: "Alta",
    workforce: {
      worforce1: 8,
      worforce2: 5,
      worforce3: 7,
      worforce4: 9,
    },
    materials: {
      material1: 2,
      material2: 5,
      material3: 3,
      material4: 8,
      material5: 7,
    },
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, veniam magni. Omnis sunt quaerat quidem, perferendis animi harum laboriosam dolorem reprehenderit vel est adipisci rerum magnam nulla itaque eaque dignissimos doloremque fuga. Odit et voluptatibus ipsa voluptatum consequuntur? Sunt accusamus tempora ea ratione officiis excepturi ipsa perspiciatis repellendus reprehenderit sapiente.",
  },
  {
    visitDate: "30/06/2023",
    name: "Eagle Pharmaceuticals, Inc.",
    customerName: "Nader Group",
    id: 48812,
    city: "Montería",
    address: "81116 Lunder Trail",
    phoneNumber: "833-770-9879",
    email: "ncustard2@cafepress.com",
    dueDate: "24/06/2023",
    priority: "Media",
    workforce: {
      worforce1: 8,
      worforce2: 5,
      worforce3: 7,
      worforce4: 9,
    },
    materials: {
      material1: 2,
      material2: 5,
      material3: 3,
      material4: 8,
      material5: 7,
    },
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, veniam magni. Omnis sunt quaerat quidem, perferendis animi harum laboriosam dolorem reprehenderit vel est adipisci rerum magnam nulla itaque eaque dignissimos doloremque fuga. Odit et voluptatibus ipsa voluptatum consequuntur? Sunt accusamus tempora ea ratione officiis excepturi ipsa perspiciatis repellendus reprehenderit sapiente.",
  },
  {
    visitDate: "12/01/2024",
    name: "Fallien Cosmeceuticals, LTD.",
    customerName: "Beatty-Stiedemann",
    id: 58830,
    city: "Cartagena",
    address: "20985 Sachs Place",
    phoneNumber: "745-933-8362",
    email: "fpapis3@msu.edu",
    dueDate: "28/08/2023",
    priority: "Baja",
    workforce: {
      worforce1: 8,
      worforce2: 5,
      worforce3: 7,
      worforce4: 9,
    },
    materials: {
      material1: 2,
      material2: 5,
      material3: 3,
      material4: 8,
      material5: 7,
    },
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, veniam magni. Omnis sunt quaerat quidem, perferendis animi harum laboriosam dolorem reprehenderit vel est adipisci rerum magnam nulla itaque eaque dignissimos doloremque fuga. Odit et voluptatibus ipsa voluptatum consequuntur? Sunt accusamus tempora ea ratione officiis excepturi ipsa perspiciatis repellendus reprehenderit sapiente.",
  },
  {
    visitDate: "01/02/2024",
    name: "Chain Drug Marketing Association Inc.",
    customerName: "Mosciski Inc",
    id: 50435,
    city: "Bucaramanga",
    address: "7 Roth Drive",
    phoneNumber: "537-296-9525",
    email: "cohanessian4@live.com",
    dueDate: "26/11/2023",
    priority: "Alta",
    workforce: {
      worforce1: 8,
      worforce2: 5,
      worforce3: 7,
      worforce4: 9,
    },
    materials: {
      material1: 2,
      material2: 5,
      material3: 3,
      material4: 8,
      material5: 7,
    },
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, veniam magni. Omnis sunt quaerat quidem, perferendis animi harum laboriosam dolorem reprehenderit vel est adipisci rerum magnam nulla itaque eaque dignissimos doloremque fuga. Odit et voluptatibus ipsa voluptatum consequuntur? Sunt accusamus tempora ea ratione officiis excepturi ipsa perspiciatis repellendus reprehenderit sapiente.",
  },
  {
    visitDate: "24/10/2023",
    name: "Jubilant HollisterStier LLC",
    customerName: "McGlynn LLC",
    id: 41048,
    city: "Pereira",
    address: "1046 Reindahl Court",
    phoneNumber: "628-979-8998",
    email: "iloftin5@amazon.com",
    dueDate: "11/06/2023",
    priority: "Media",
    workforce: {
      worforce1: 8,
      worforce2: 5,
      worforce3: 7,
      worforce4: 9,
    },
    materials: {
      material1: 2,
      material2: 5,
      material3: 3,
      material4: 8,
      material5: 7,
    },
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, veniam magni. Omnis sunt quaerat quidem, perferendis animi harum laboriosam dolorem reprehenderit vel est adipisci rerum magnam nulla itaque eaque dignissimos doloremque fuga. Odit et voluptatibus ipsa voluptatum consequuntur? Sunt accusamus tempora ea ratione officiis excepturi ipsa perspiciatis repellendus reprehenderit sapiente.",
  },
  {
    visitDate: "26/04/2024",
    name: "L?Oreal USA Products Inc",
    customerName: "Koelpin LLC",
    id: 94033,
    city: "Barranquilla",
    address: "164 Springs Terrace",
    phoneNumber: "993-415-5212",
    email: "bmaudsley6@alexa.com",
    dueDate: "01/07/2023",
    priority: "Baja",
    workforce: {
      worforce1: 8,
      worforce2: 5,
      worforce3: 7,
      worforce4: 9,
    },
    materials: {
      material1: 2,
      material2: 5,
      material3: 3,
      material4: 8,
      material5: 7,
    },
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, veniam magni. Omnis sunt quaerat quidem, perferendis animi harum laboriosam dolorem reprehenderit vel est adipisci rerum magnam nulla itaque eaque dignissimos doloremque fuga. Odit et voluptatibus ipsa voluptatum consequuntur? Sunt accusamus tempora ea ratione officiis excepturi ipsa perspiciatis repellendus reprehenderit sapiente.",
  },
  {
    visitDate: "28/06/2023",
    name: "Uriel Pharmacy Inc.",
    customerName: "Olson, Harber and Mohr",
    id: 64533,
    city: "Cartagena",
    address: "9 Del Mar Point",
    phoneNumber: "759-527-3707",
    email: "ebednell7@geocities.com",
    dueDate: "27/06/2024",
    priority: "Alta",
    workforce: {
      worforce1: 8,
      worforce2: 5,
      worforce3: 7,
      worforce4: 9,
    },
    materials: {
      material1: 2,
      material2: 5,
      material3: 3,
      material4: 8,
      material5: 7,
    },
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, veniam magni. Omnis sunt quaerat quidem, perferendis animi harum laboriosam dolorem reprehenderit vel est adipisci rerum magnam nulla itaque eaque dignissimos doloremque fuga. Odit et voluptatibus ipsa voluptatum consequuntur? Sunt accusamus tempora ea ratione officiis excepturi ipsa perspiciatis repellendus reprehenderit sapiente.",
  },
  {
    visitDate: "18/08/2023",
    name: "Roxane Laboratories, Inc.",
    customerName: "Huels, Hyatt and Friesen",
    id: 70687,
    city: "Popayán",
    address: "715 Fallview Parkway",
    phoneNumber: "269-591-9621",
    email: "mzolini8@nsw.gov.au",
    dueDate: "08/06/2024",
    priority: "Alta",
    workforce: {
      worforce1: 8,
      worforce2: 5,
      worforce3: 7,
      worforce4: 9,
    },
    materials: {
      material1: 2,
      material2: 5,
      material3: 3,
      material4: 8,
      material5: 7,
    },
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, veniam magni. Omnis sunt quaerat quidem, perferendis animi harum laboriosam dolorem reprehenderit vel est adipisci rerum magnam nulla itaque eaque dignissimos doloremque fuga. Odit et voluptatibus ipsa voluptatum consequuntur? Sunt accusamus tempora ea ratione officiis excepturi ipsa perspiciatis repellendus reprehenderit sapiente.",
  },
  {
    visitDate: "27/07/2023",
    name: "Beiersdorf Inc",
    customerName: "Roberts, Abbott and Kihn",
    id: 59903,
    city: "Manizales",
    address: "615 Hallows Street",
    phoneNumber: "714-408-3328",
    email: "hrathbone9@w3.org",
    dueDate: "23/06/2023",
    priority: "Alta",
    workforce: {
      worforce1: 8,
      worforce2: 5,
      worforce3: 7,
      worforce4: 9,
    },
    materials: {
      material1: 2,
      material2: 5,
      material3: 3,
      material4: 8,
      material5: 7,
    },
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, veniam magni. Omnis sunt quaerat quidem, perferendis animi harum laboriosam dolorem reprehenderit vel est adipisci rerum magnam nulla itaque eaque dignissimos doloremque fuga. Odit et voluptatibus ipsa voluptatum consequuntur? Sunt accusamus tempora ea ratione officiis excepturi ipsa perspiciatis repellendus reprehenderit sapiente.",
  },
];
